implement task
romazan07/book-store pull request #2
Opened 2024-10-08 20:58 UTC by romazan07

add dto, mapper, controller. Add findById method into repository. Use EntityNotFoundException.

2024-10-09 08:35 UTC, ahoienko approved these changes

2024-12-27 07:20 UTC, liliia-ponomarenko requested changes
Good job! But fix comments and move your solution to the separate PR

2024-12-27 07:20 UTC, liliia-ponomarenko commented on src/main/java/mate/academy/bookstore/config/MapperConfig.java
> +package mate.academy.bookstore.config;
avoid using mate academy in your project

2024-12-27 07:20 UTC, liliia-ponomarenko commented on src/main/java/mate/academy/bookstore/controller/BookController.java
> +    }
Remove this endpoint and all relevant code. You will implement the search endpoint in the next task

2024-12-27 07:20 UTC, liliia-ponomarenko commented on src/main/java/mate/academy/bookstore/controller/BookController.java
> +    @PostMapping
ResponseStatus.CREATED

2024-12-27 07:20 UTC, liliia-ponomarenko commented on src/main/java/mate/academy/bookstore/controller/BookController.java
> +@RequestMapping(value = "/books")
```suggestion
@RequestMapping("/books")
```

2024-12-27 07:20 UTC, liliia-ponomarenko commented on src/main/java/mate/academy/bookstore/service/impl/BookServiceImpl.java
> +                () -> new EntityNotFoundException("Can't find the book by id = " + id)));
Let’s  use your custom EntityNotFoundException

2024-12-27 13:45 UTC, JJJazl approved these changes
Left some minor comments, but I am sure you can move on. Please, fix them before next task)

2024-12-27 13:45 UTC, JJJazl commented on src/main/java/com/bookstore/BookStoreApplication.java
> +@RequiredArgsConstructor
```suggestion
```

2024-12-27 13:45 UTC, JJJazl commented on src/main/java/com/bookstore/controller/BookController.java
> +    @DeleteMapping("/{id}")
```suggestion
    @DeleteMapping("/{id}")
    @ResponseStatus(HttpStatus.NO_CONTENT)
```

2024-12-27 13:45 UTC, JJJazl commented on src/main/java/com/bookstore/service/impl/BookServiceImpl.java
> +@RequiredArgsConstructor
```suggestion
@Service
@RequiredArgsConstructor
@Transactional
```

2024-12-27 13:45 UTC, JJJazl commented on src/main/java/com/bookstore/exception/EntityNotFoundException.java
> +        super(entity + " not found with id = " + id);
Interesting solution, I'll take note))
```suggestion
        super(String.format("%s not found with id = %s", entity, id));
```

2024-12-27 13:45 UTC, JJJazl commented on src/main/java/com/bookstore/service/impl/BookServiceImpl.java
> +        Book updateBook = bookRepository.save(book);
By the way, with the `@Transactional` annotation you can update your entities without calling the `save()` method. Read about the dirty-checking mechanism in Hibernate. Note that JPA and Hibernate do not have an `update()` method or anything like that. You can think of the `merge()` method, but its purpose is to add an entity to the session, the update will happen through dirty-checking

2025-02-18 20:51 UTC, merged